//export const CREATE_COURSE = 'CREATE_COURSE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';

export const LOAD_BEER_SUCCESS = 'LOAD_BEER_SUCCESS';
//export const LOAD_BEER_SUCCESS = 'LOAD_BEER_SUCCESS';